<?php part('page-hero', [
    'crumb' => 'Terms & Conditions',
    'title' => 'Terms & Conditions',
    'lede'  => 'The terms governing ClientcareX performance marketing and business automation engagements.',
]) ?>

<section class="section">
  <div class="container prose">

    <?php part('notice', ['html' => '<strong>Draft for review.</strong> These terms describe the commercial
        model as published on this site. Have them reviewed by your legal
        adviser and aligned with your signed client agreements before go-live.']) ?>

    <h2>1. Agreement</h2>
    <p>
      These terms form an agreement between you (or the organisation you
      represent) and <?= COMPANY ?> (“ClientcareX”, “we”, “us”). They apply
      alongside the engagement letter, statement of work or scope document
      signed for your specific engagement. Where the two differ, the signed
      document takes precedence.
    </p>

    <h2>2. Services</h2>
    <p>We provide two services, either separately or together:</p>
    <ul>
      <li><strong>Performance marketing</strong> — we plan, fund and run paid and organic acquisition campaigns on your behalf, charged as a share of the revenue those campaigns generate.</li>
      <li><strong>Business automation</strong> — we map your processes, agree a written scope, and build the automation described in it for a fixed fee.</li>
    </ul>

    <h2>3. Performance marketing fees</h2>
    <ul>
      <li>Our fee is a percentage of Attributed Revenue, between <?= SHARE_MIN ?> and <?= SHARE_MAX ?>, fixed in writing before any campaign goes live.</li>
      <li>There is no setup fee, onboarding fee, retainer, minimum spend or management fee charged in addition to that percentage.</li>
      <li>We fund campaign costs including advertising spend, our personnel, creative production, software subscriptions, licensed assets and tracking infrastructure. These are not passed through to you.</li>
      <li>You remain responsible for your own product, fulfilment, and any payment gateway or marketplace fees on your own sales.</li>
      <li>Fees are exclusive of applicable taxes.</li>
    </ul>

    <h2>4. Attributed Revenue</h2>
    <p>
      “Attributed Revenue” means revenue that both parties agree was generated by
      our campaigns, measured by the attribution method recorded in your
      engagement letter — which may include tracked conversions, dedicated
      landing pages, unique coupon codes, call-tracking numbers or a CRM source
      stage. It is calculated net of taxes and net of refunds, cancellations,
      returns, chargebacks and amounts never collected, and is reconciled
      against your own sales records each month before invoicing. Measurement,
      reconciliation and dispute handling are set out in the
      <a href="<?= url('refund') ?>">Billing &amp; Refund Policy</a>, which forms part of
      these terms.
    </p>

    <h2>5. Business automation fees</h2>
    <ul>
      <li>Discovery and the resulting workflow map are provided free of charge and without obligation.</li>
      <li>The build fee is fixed against the agreed scope document. It is not charged per user and does not carry a recurring licence.</li>
      <li>Work outside the agreed scope is quoted separately and only carried out once approved in writing.</li>
      <li>Ongoing support, hosting or third-party subscriptions, where you ask us to arrange them, are quoted separately and stated plainly.</li>
      <li>Payment milestones are set out in the scope document.</li>
    </ul>

    <h2>6. Your responsibilities</h2>
    <ul>
      <li>Provide timely access to ad accounts, analytics, CRM, sales records and brand assets, and keep that access active for the term.</li>
      <li>Provide accurate sales and refund data for reconciliation.</li>
      <li>Ensure the claims, offers and products we advertise are lawful, accurate and yours to sell.</li>
      <li>Sign off on creative, offers and landing pages within a reasonable time.</li>
      <li>Ensure outreach data you supply for SMS, WhatsApp, email or calling was collected with valid consent.</li>
      <li>Do not run competing campaigns that make attribution impossible without telling us first.</li>
    </ul>

    <h2>7. Ownership</h2>
    <p>
      You own your customer data, your brand assets and your ad accounts.
      Creative produced specifically for your campaigns is assigned to you on
      payment of the fees due for the period in which it was produced. Our own
      tooling, internal frameworks, templates and know-how remain ours, and
      nothing in an engagement transfers them.
    </p>

    <h2>8. Confidentiality</h2>
    <p>
      Each party will keep the other's non-public commercial information
      confidential and use it only to perform the engagement. Neither party will
      name the other as a client publicly without written consent.
    </p>

    <h2>9. Term and termination</h2>
    <ul>
      <li>A performance marketing engagement may be ended by either party on 30 days' written notice.</li>
      <li>On termination we stop campaigns and hand back account access. The revenue share remains payable on Attributed Revenue generated up to the end of the notice period, plus any tracked repeat revenue for the tail period stated in your engagement letter.</li>
      <li>An automation engagement may be ended for convenience; you pay for work completed and accepted to that point.</li>
      <li>Either party may terminate immediately for material breach that remains uncured 30 days after written notice.</li>
    </ul>

    <h2>10. No guarantee of results</h2>
    <p>
      We fund campaigns at our own risk and are paid only from the revenue they
      produce, but we do not warrant any particular volume of revenue, cost per
      acquisition or return. Nothing on this site is a guarantee of results.
    </p>

    <h2>11. Liability</h2>
    <p>
      To the extent permitted by law, neither party is liable for indirect or
      consequential loss, and our aggregate liability is limited to the fees paid
      by you to us in the twelve months preceding the claim.
    </p>

    <h2>12. Governing law</h2>
    <p>
      These terms are governed by the laws of India, and the courts having
      jurisdiction over our registered office will hear any dispute.
    </p>

    <h2>13. Contact</h2>
    <p>
      Questions about these terms:
      <a href="mailto:<?= EMAIL ?>"><?= EMAIL ?></a> or <?= PHONE ?>.
    </p>

    <p class="muted" style="margin-top:2rem">Last updated: <?= date('Y') ?></p>
  </div>
</section>
